import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import Script from "next/script";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <main className="flex h-screen flex-col bg-background dark:bg-[#111] transition-colors duration-300 gap-4 main-noise-bg">
            <Header />
            {children}
            <Toaster />
            <Footer />
          </main>
        </ThemeProvider>
        <Script
          data-name="BMC-Widget" 
          data-cfasync="false" 
          src="https://cdnjs.buymeacoffee.com/1.0.0/widget.prod.min.js" 
          data-id="Lilian.ada" 
          data-description="Support me on Buy me a coffee!" 
          data-message="Hiiiii❤️, thank you for checking out this website.You can now support work by buying me a cup of coffee☕️" 
          data-color="#BD5FFF" 
          data-position="Right" 
          data-x_margin="18" 
          data-y_margin="18"
          strategy="lazyOnload"
        />
      </body>
    </html>
  );
}
