"use client"

import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"

type AboutDialogProps = {
  open: boolean
  onOpenChange: (open: boolean) => void
  trigger?: React.ReactNode
}

export default function AboutDialog({ open, onOpenChange, trigger }: AboutDialogProps) {
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      {trigger && <DialogTrigger asChild>{trigger}</DialogTrigger>}
      <DialogContent className="bg-white dark:bg-zinc-900 border-zinc-200 dark:border-zinc-800 max-h-[90vh] overflow-y-auto max-w-lg w-full">
        <DialogHeader>
          <DialogTitle className="text-zinc-800 dark:text-zinc-200">About the Rich Text &lt;=&gt; Markdown Editor</DialogTitle>
          <DialogDescription className="text-zinc-600 dark:text-zinc-400 pt-4 space-y-4 text-left">
            <p>
              Welcome to the <strong>Rich Text to Markdown Editor</strong> (and vice-versa!), a powerful online tool from <a href="https://lilyslab.xyz" target="_blank" rel="noopener noreferrer" className="font-medium underline underline-offset-4 text-zinc-600 dark:text-zinc-300 hover:text-zinc-900 dark:hover:text-zinc-100">Lily&apos;s Lab</a> designed for developers, writers, and content creators.
            </p>
            <p>
              Effortlessly switch between visually editing content in a <strong>WYSIWYG (What You See Is What You Get) rich text editor</strong> and the clean, portable <strong>Markdown format</strong>. Whether you need to convert complex HTML generated by content management systems into simple Markdown, or write in Markdown and preview the rendered <strong>HTML / rich text output</strong>, this tool streamlines your workflow.
            </p>
            <p>
              <strong>Key Features &amp; Benefits:</strong>
              <ul className="list-disc ml-5 mt-2 space-y-1">
                <li><strong>Seamless Bidirectional Conversion:</strong> Easily convert <strong>HTML to Markdown online</strong> using <code className="font-mono text-xs bg-zinc-100 dark:bg-zinc-800 p-0.5 rounded">turndown.js</code>, or convert <strong>Markdown to HTML</strong> using <code className="font-mono text-xs bg-zinc-100 dark:bg-zinc-800 p-0.5 rounded">marked.js</code>.</li>
                <li><strong>Intuitive Rich Text Editor:</strong> Utilizes <code className="font-mono text-xs bg-zinc-100 dark:bg-zinc-800 p-0.5 rounded">react-quill</code> for a familiar and powerful editing experience.</li>
                <li><strong>Live Preview:</strong> Instantly see the results of your conversion as you type.</li>
                <li><strong>Clean Output:</strong> Generates well-formatted Markdown or HTML suitable for various platforms.</li>
                <li><strong>Developer &amp; Writer Friendly:</strong> Perfect for drafting blog posts, documentation, notes, or converting existing web content.
                </li>
              </ul>
            </p>
            <p>
              <strong>Why use this editor?</strong> <br />
              - Simplify content migration between different platforms.<br />
              - Standardize content into the versatile Markdown format.<br />
              - Quickly draft formatted text without complex HTML coding.<br />
              - Preview how your Markdown will render as rich text.
            </p>
            <p>
              This <strong>online Markdown Editor</strong> is a free tool provided by <a href="https://lilyslab.xyz" target="_blank" rel="noopener noreferrer" className="font-medium underline underline-offset-4 text-zinc-600 dark:text-zinc-300 hover:text-zinc-900 dark:hover:text-zinc-100">Lily&apos;s Lab</a>. We aim to create useful resources for the web development community.
            </p>
            <p>
              Find a bug or want to contribute? Check out the <a href="https://github.com/Lilianada/RichText-to-Markdown-Editor/fork" target="_blank" rel="noopener noreferrer" className="font-medium underline underline-offset-4 text-zinc-600 dark:text-zinc-300 hover:text-zinc-900 dark:hover:text-zinc-100">GitHub repository</a> Fork the project and submit your improvements!
            </p>
          </DialogDescription>
        </DialogHeader>
      </DialogContent>
    </Dialog>
  )
}